# Generated by Django 4.0.4 on 2022-05-29 08:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_cryptopricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptopricehistory',
            name='price_updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
