# Generated by Django 4.0.4 on 2022-05-29 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_cryptopricehistory_price_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
